const COMMON_PLAYER = ['combat','myhp','mypower','mod','cooldown','mybuff','stance','stealth','moving','usable'];
const COMMON_TARGET = ['harm','help','alive','hp','debuff','meleerange','inrange'];

const COMMANDS = [
  { cmd: '/cast', human: 'Cast a spell', hasSpell: true, common: true },
  { cmd: '/use', human: 'Use an item', hasSpell: true, common: true },
  { cmd: '/startattack', human: 'Start attacking', hasSpell: false, common: true },
  { cmd: '/stopcasting', human: 'Stop casting', hasSpell: false, common: true },
  { cmd: '/cancelaura', human: 'Cancel a buff', hasSpell: true, common: true },
  { cmd: '/equip', human: 'Equip an item', hasSpell: true },
  { cmd: '/castsequence', human: 'Cast a sequence', hasSpell: true },
  { cmd: '/castpet', human: 'Cast a pet spell', hasSpell: true },
  { cmd: '/stopattack', human: 'Stop attacking', hasSpell: false },
  { cmd: '/unshift', human: 'Leave shapeshift form', hasSpell: false },
  { cmd: '/stopmacro', human: 'Stop this macro', hasSpell: false },
  { cmd: '/skipmacro', human: 'Skip this submacro', hasSpell: false },
  { cmd: '/firstaction', human: 'First successful cast wins', hasSpell: false },
  { cmd: '/nofirstaction', human: 'End first-action mode', hasSpell: false },
  { cmd: '/target', human: 'Target an enemy', hasSpell: false },
  { cmd: '/cleartarget', human: 'Clear my target', hasSpell: false },
  { cmd: '/unqueue', human: 'Cancel queued spell', hasSpell: false },
  { cmd: '/petattack', human: 'Pet: attack', hasSpell: false },
  { cmd: '/petfollow', human: 'Pet: follow', hasSpell: false },
  { cmd: '/petpassive', human: 'Pet: passive', hasSpell: false },
  { cmd: '/petdefensive', human: 'Pet: defensive', hasSpell: false },
  { cmd: '/petwait', human: 'Pet: stay', hasSpell: false },
  { cmd: '/petaggressive', human: 'Pet: aggressive', hasSpell: false },
  { cmd: '/quickheal', human: 'Smart heal', hasSpell: false },
  { cmd: '/equip13', human: 'Equip trinket 1', hasSpell: true },
  { cmd: '/equip14', human: 'Equip trinket 2', hasSpell: true },
  { cmd: '/runmacro', human: 'Run another macro', hasSpell: true },
  { cmd: '/retarget', human: 'Retarget nearest enemy', hasSpell: false },
  { cmd: '/equipmh', human: 'Equip main hand', hasSpell: true },
  { cmd: '/equipoh', human: 'Equip off hand', hasSpell: true },
  { cmd: '/applymain', human: 'Apply to main hand', hasSpell: true },
  { cmd: '/applyoff', human: 'Apply to off hand', hasSpell: true },
  { cmd: '#showtooltip', human: 'Show tooltip for', hasSpell: true },
];

const TARGETS = [
  { value: '', human: 'My target', syntax: '@target' },
  { value: '@player', human: 'Myself', syntax: '@player' },
  { value: '@mouseover', human: 'Whoever I\'m hovering over', syntax: '@mouseover' },
  { value: '@focus', human: 'My focus target', syntax: '@focus' },
  { value: '@pet', human: 'My pet', syntax: '@pet' },
  { value: '@party1', human: 'Party member 1', syntax: '@party1' },
  { value: '@party2', human: 'Party member 2', syntax: '@party2' },
  { value: '@party3', human: 'Party member 3', syntax: '@party3' },
  { value: '@party4', human: 'Party member 4', syntax: '@party4' },
  { value: '@targettarget', human: 'My target\'s target', syntax: '@targettarget' },
  { value: '@focustarget', human: 'My focus\'s target', syntax: '@focustarget' },
  { value: '@targetowner', human: 'My target\'s owner', syntax: '@targetowner' },
  { value: '@mouseovertarget', human: 'My mouseover\'s target', syntax: '@mouseovertarget' },
  { value: '@party1pet', human: 'Party 1\'s pet', syntax: '@party1pet' },
  { value: '@party2pet', human: 'Party 2\'s pet', syntax: '@party2pet' },
  { value: '@party3pet', human: 'Party 3\'s pet', syntax: '@party3pet' },
  { value: '@party4pet', human: 'Party 4\'s pet', syntax: '@party4pet' },
  { value: '@mark1', human: 'Skull mark', syntax: '@mark1' },
  { value: '@mark2', human: 'Cross mark', syntax: '@mark2' },
  { value: '@mark3', human: 'Square mark', syntax: '@mark3' },
  { value: '@mark4', human: 'Moon mark', syntax: '@mark4' },
  { value: '@mark5', human: 'Triangle mark', syntax: '@mark5' },
  { value: '@mark6', human: 'Diamond mark', syntax: '@mark6' },
  { value: '@mark7', human: 'Circle mark', syntax: '@mark7' },
  { value: '@mark8', human: 'Star mark', syntax: '@mark8' },
];

const CONDITIONALS = [
  // ==================== PLAYER ====================
  // -- Health & Survival --
  { name: 'combat', scope: 'player', cat: 'Health & Survival', type: 'boolean', negatable: true,
    human: "I'm in combat", humanNeg: "I'm not in combat" },
  { name: 'myhp', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "My health is {op} {value}%" },
  { name: 'mypower', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "My mana/rage/energy is {op} {value}%" },
  { name: 'stealth', scope: 'player', cat: 'Health & Survival', type: 'boolean', negatable: true,
    human: "I'm stealthed", humanNeg: "I'm not stealthed" },
  { name: 'moving', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: true,
    human: "I'm moving", humanNeg: "I'm standing still" },
  { name: 'rooted', scope: 'player', cat: 'Health & Survival', type: 'boolean', negatable: true,
    human: "I'm rooted", humanNeg: "I'm not rooted", requires: 'Nampower v2.36' },
  { name: 'swimming', scope: 'player', cat: 'Health & Survival', type: 'boolean', negatable: true,
    human: "I'm swimming", humanNeg: "I'm not swimming" },
  { name: 'resting', scope: 'player', cat: 'Health & Survival', type: 'boolean', negatable: true,
    human: "I'm in a rest area", humanNeg: "I'm not in a rest area" },
  { name: 'myrawhp', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "My raw HP is {op} {value}" },
  { name: 'myhplost', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "I'm missing {op} {value} HP" },
  { name: 'myrawpower', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "My raw power is {op} {value}" },
  { name: 'mypowerlost', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "I'm missing {op} {value} power" },
  { name: 'druidmana', scope: 'player', cat: 'Health & Survival', type: 'comparison', negatable: false,
    human: "My mana (in form) is {op} {value}" },

  // -- My Buffs & Effects --
  { name: 'mybuff', scope: 'player', cat: 'My Buffs & Effects', type: 'spellComparison', negatable: true,
    human: "I have {spell}", humanNeg: "I don't have {spell}" },
  { name: 'mydebuff', scope: 'player', cat: 'My Buffs & Effects', type: 'spellComparison', negatable: true,
    human: "{spell} is on me", humanNeg: "{spell} is not on me" },
  { name: 'mycc', scope: 'player', cat: 'My Buffs & Effects', type: 'value', negatable: true,
    human: "I'm {value} (crowd controlled)", humanNeg: "I'm not crowd controlled",
    options: ['stun','fear','root','snare','slow','sleep','charm','polymorph','banish','horror','disorient','silence','disarm','daze','freeze','shackle'] },
  { name: 'mybuffcount', scope: 'player', cat: 'My Buffs & Effects', type: 'comparison', negatable: true,
    human: "My buff count is {op} {value}" },
  { name: 'mybuffcapped', scope: 'player', cat: 'My Buffs & Effects', type: 'boolean', negatable: true,
    human: "My buff bar is full", humanNeg: "My buff bar has room", requires: 'Nampower v2.20' },
  { name: 'mydebuffcapped', scope: 'player', cat: 'My Buffs & Effects', type: 'boolean', negatable: true,
    human: "My debuff bar is full", humanNeg: "My debuff bar has room", requires: 'Nampower v2.20' },

  // -- My Abilities --
  { name: 'cooldown', scope: 'player', cat: 'My Abilities', type: 'spellComparison', negatable: true,
    human: "{spell} is on cooldown", humanNeg: "{spell} is off cooldown" },
  { name: 'usable', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: true,
    human: "{spell} is usable", humanNeg: "{spell} is not usable" },
  { name: 'reactive', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: true,
    human: "{spell} has procced", humanNeg: "{spell} hasn't procced" },
  { name: 'known', scope: 'player', cat: 'My Abilities', type: 'spellComparison', negatable: true,
    human: "I know {spell}", humanNeg: "I don't know {spell}" },
  { name: 'gcd', scope: 'player', cat: 'My Abilities', type: 'comparison', negatable: true,
    human: "GCD is active", humanNeg: "GCD is not active" },
  { name: 'selfcasting', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: true,
    human: "I'm casting", humanNeg: "I'm not casting" },
  { name: 'channeled', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: true,
    human: "I'm channeling", humanNeg: "I'm not channeling" },
  { name: 'checkcasting', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: false,
    human: "I'm not casting" },
  { name: 'checkchanneled', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: false,
    human: "I'm not channeling" },
  { name: 'cdgcd', scope: 'player', cat: 'My Abilities', type: 'spellComparison', negatable: true,
    human: "{spell} CD (incl GCD) is {op} {value}s" },
  { name: 'spellcasttime', scope: 'player', cat: 'My Abilities', type: 'spellComparison', negatable: true,
    human: "{spell} cast time is {op} {value}s" },
  { name: 'queuedspell', scope: 'player', cat: 'My Abilities', type: 'spell', negatable: true,
    human: "{spell} is queued", humanNeg: "No spell queued", requires: 'Nampower v2.12' },
  { name: 'onswingpending', scope: 'player', cat: 'My Abilities', type: 'boolean', negatable: true,
    human: "On-swing spell pending", humanNeg: "No on-swing pending", requires: 'Nampower v2.12' },

  // -- Gear & Stance --
  { name: 'stance', scope: 'player', cat: 'Gear & Stance', type: 'value', negatable: true,
    human: "I'm in stance {value}", humanNeg: "I'm not in stance {value}",
    options: ['0','1','2','3','4','5','6'], hint: '1=Battle, 2=Defensive, 3=Berserker' },
  { name: 'form', scope: 'player', cat: 'Gear & Stance', type: 'value', negatable: true,
    human: "I'm in form {value}", humanNeg: "I'm not in form {value}",
    options: ['0','1','2','3','4','5','6'], hint: '0=caster, 1-6=forms' },
  { name: 'equipped', scope: 'player', cat: 'Gear & Stance', type: 'value', negatable: true,
    human: "I have {value} equipped", humanNeg: "I don't have {value} equipped",
    options: ['Daggers','Swords','Maces','Axes','Staves','Polearms','Fist Weapons','Guns','Bows','Crossbows','Wands','Shields','Thrown'] },
  { name: 'mhimbue', scope: 'player', cat: 'Gear & Stance', type: 'spellComparison', negatable: true,
    human: "Main hand has {spell}", humanNeg: "Main hand has no imbue" },
  { name: 'ohimbue', scope: 'player', cat: 'Gear & Stance', type: 'spellComparison', negatable: true,
    human: "Off hand has {spell}", humanNeg: "Off hand has no imbue" },

  // -- Resources --
  { name: 'combo', scope: 'player', cat: 'Resources', type: 'comparison', negatable: true,
    human: "I have {op} {value} combo points" },
  { name: 'inbag', scope: 'player', cat: 'Resources', type: 'spellComparison', negatable: true,
    human: "I have {spell} in my bags", humanNeg: "I don't have {spell} in bags" },

  // -- Modifiers --
  { name: 'mod', scope: 'player', cat: 'Modifiers', type: 'value', negatable: true,
    human: "I'm holding {value}", humanNeg: "I'm not holding {value}",
    options: ['alt','ctrl','shift'] },
  { name: 'keydown', scope: 'player', cat: 'Modifiers', type: 'value', negatable: true,
    human: "Key {value} is held", humanNeg: "Key {value} is not held", requires: 'Nampower v2.41' },
  { name: 'mouseuse', scope: 'player', cat: 'Modifiers', type: 'boolean', negatable: false,
    human: "Auto-place AoE at cursor" },

  // -- Auto-Attack --
  { name: 'swingtimer', scope: 'player', cat: 'Auto-Attack', type: 'comparison', negatable: true,
    human: "Swing timer past {op} {value}%", requires: 'SP_SwingTimer' },
  { name: 'rangedtimer', scope: 'player', cat: 'Auto-Attack', type: 'comparison', negatable: true,
    human: "Ranged timer past {op} {value}%", requires: 'SP_SwingTimer' },
  { name: 'rangedclip', scope: 'player', cat: 'Auto-Attack', type: 'boolean', negatable: true,
    human: "Cast will clip auto-shot", humanNeg: "Cast won't clip auto-shot", requires: 'SP_SwingTimer' },
  { name: 'slamclip', scope: 'player', cat: 'Auto-Attack', type: 'boolean', negatable: true,
    human: "Slam will clip melee", humanNeg: "Slam won't clip melee", requires: 'SP_SwingTimer' },
  { name: 'nextslamclip', scope: 'player', cat: 'Auto-Attack', type: 'boolean', negatable: true,
    human: "Instant will clip next Slam", humanNeg: "Instant won't clip next Slam", requires: 'SP_SwingTimer' },
  { name: 'lastswing', scope: 'player', cat: 'Auto-Attack', type: 'value', negatable: true,
    human: "Last swing was a {value}",
    options: ['crit','glancing','miss','dodge','parry','blocked','offhand','mainhand','hit'], requires: 'Nampower v2.24' },
  { name: 'incominghit', scope: 'player', cat: 'Auto-Attack', type: 'value', negatable: true,
    human: "Incoming hit is a {value}",
    options: ['crit','glancing','crushing','miss','dodge','parry','blocked','hit'], requires: 'Nampower v2.24' },
  { name: 'stimer', scope: 'player', cat: 'Auto-Attack', type: 'comparison', negatable: true,
    human: "Swing timer past {op} {value}%", requires: 'SP_SwingTimer' },
  { name: 'rtimer', scope: 'player', cat: 'Auto-Attack', type: 'comparison', negatable: true,
    human: "Ranged timer past {op} {value}%", requires: 'SP_SwingTimer' },

  // -- Context --
  { name: 'hastarget', scope: 'player', cat: 'Context', type: 'boolean', negatable: false,
    human: "I have a target" },
  { name: 'notarget', scope: 'player', cat: 'Context', type: 'boolean', negatable: false,
    human: "I have no target" },
  { name: 'group', scope: 'player', cat: 'Context', type: 'value', negatable: true,
    human: "I'm in a {value}", humanNeg: "I'm not grouped",
    options: ['party','raid'] },
  { name: 'pet', scope: 'player', cat: 'Context', type: 'value', negatable: true,
    human: "I have a pet", humanNeg: "I don't have a pet" },
  { name: 'zone', scope: 'player', cat: 'Context', type: 'value', negatable: true,
    human: "I'm in {value}", humanNeg: "I'm not in {value}" },
  { name: 'mylevel', scope: 'player', cat: 'Context', type: 'comparison', negatable: false,
    human: "My level is {op} {value}" },
  { name: 'stat', scope: 'player', cat: 'Context', type: 'stat', negatable: true,
    human: "My {stat} is {op} {value}",
    options: ['str','agi','stam','int','spi','ap','rap','healing','spell_power','arcane_power','fire_power','frost_power','nature_power','shadow_power','armor','defense','arcane_res','fire_res','frost_res','nature_res','shadow_res'] },

  // ==================== TARGET ====================
  // -- Basics --
  { name: 'harm', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "Target is an enemy", humanNeg: "Target is not an enemy" },
  { name: 'help', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "Target is friendly", humanNeg: "Target is not friendly" },
  { name: 'alive', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "Target is alive", humanNeg: "Target is dead" },
  { name: 'dead', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "Target is dead", humanNeg: "Target is alive" },
  { name: 'exists', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "I have a target", humanNeg: "I have no target" },
  { name: 'isplayer', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "Target is a player", humanNeg: "Target is an NPC" },
  { name: 'isnpc', scope: 'target', cat: 'Basics', type: 'boolean', negatable: true,
    human: "Target is an NPC", humanNeg: "Target is a player" },

  // -- Target Health --
  { name: 'hp', scope: 'target', cat: 'Target Health', type: 'comparison', negatable: false,
    human: "Target health is {op} {value}%" },
  { name: 'rawhp', scope: 'target', cat: 'Target Health', type: 'comparison', negatable: false,
    human: "Target raw HP is {op} {value}" },
  { name: 'hplost', scope: 'target', cat: 'Target Health', type: 'comparison', negatable: false,
    human: "Target missing {op} {value} HP" },
  { name: 'power', scope: 'target', cat: 'Target Health', type: 'comparison', negatable: false,
    human: "Target power is {op} {value}%" },
  { name: 'rawpower', scope: 'target', cat: 'Target Health', type: 'comparison', negatable: false,
    human: "Target raw power is {op} {value}" },
  { name: 'powerlost', scope: 'target', cat: 'Target Health', type: 'comparison', negatable: false,
    human: "Target missing {op} {value} power" },
  { name: 'powertype', scope: 'target', cat: 'Target Health', type: 'value', negatable: true,
    human: "Target uses {value}", humanNeg: "Target doesn't use {value}",
    options: ['mana','rage','energy'] },

  // -- Target Buffs --
  { name: 'buff', scope: 'target', cat: 'Target Buffs', type: 'spellComparison', negatable: true,
    human: "Target has {spell}", humanNeg: "Target doesn't have {spell}" },
  { name: 'debuff', scope: 'target', cat: 'Target Buffs', type: 'spellComparison', negatable: true,
    human: "Target has {spell} debuff", humanNeg: "Target doesn't have {spell}",
    humanTime: "{spell} has {op} {value}s left on target" },
  { name: 'cc', scope: 'target', cat: 'Target Buffs', type: 'value', negatable: true,
    human: "Target is {value}", humanNeg: "Target is not {value}",
    options: ['stun','fear','root','snare','slow','sleep','charm','polymorph','banish','horror','disorient','silence','disarm','daze','freeze','shackle'] },
  { name: 'immune', scope: 'target', cat: 'Target Buffs', type: 'value', negatable: true,
    human: "Target is immune to {value}", humanNeg: "Target is not immune to {value}",
    options: ['physical','fire','frost','nature','shadow','arcane','holy','bleed','stun','fear','root','snare','sleep','charm','polymorph','banish','horror','disorient','silence'] },
  { name: 'buffcapped', scope: 'target', cat: 'Target Buffs', type: 'boolean', negatable: true,
    human: "Target buff bar is full", humanNeg: "Target buff bar has room", requires: 'Nampower v2.20' },
  { name: 'debuffcapped', scope: 'target', cat: 'Target Buffs', type: 'boolean', negatable: true,
    human: "Target debuff bar is full", humanNeg: "Target debuff bar has room", requires: 'Nampower v2.20' },

  // -- Target Casting --
  { name: 'casting', scope: 'target', cat: 'Target Casting', type: 'spell', negatable: true,
    human: "Target is casting", humanNeg: "Target is not casting" },
  { name: 'casttime', scope: 'target', cat: 'Target Casting', type: 'comparison', negatable: true,
    human: "Target cast has {op} {value}s left" },
  { name: 'channeltime', scope: 'target', cat: 'Target Casting', type: 'comparison', negatable: true,
    human: "Target channel has {op} {value}s left" },

  // -- Target Identity --
  { name: 'class', scope: 'target', cat: 'Target Identity', type: 'value', negatable: true,
    human: "Target is a {value}", humanNeg: "Target is not a {value}",
    options: ['Warrior','Paladin','Hunter','Rogue','Priest','Shaman','Mage','Warlock','Druid'] },
  { name: 'type', scope: 'target', cat: 'Target Identity', type: 'value', negatable: true,
    human: "Target is a {value}", humanNeg: "Target is not a {value}",
    options: ['Beast','Demon','Dragonkin','Elemental','Giant','Humanoid','Mechanical','Undead','Critter'] },
  { name: 'level', scope: 'target', cat: 'Target Identity', type: 'comparison', negatable: false,
    human: "Target level is {op} {value}" },
  { name: 'name', scope: 'target', cat: 'Target Identity', type: 'value', negatable: true,
    human: "Target name is {value}", humanNeg: "Target name is not {value}" },

  // -- Range & Position --
  { name: 'meleerange', scope: 'target', cat: 'Range & Position', type: 'countMode', negatable: true,
    human: "Target is in melee range", humanNeg: "Target is not in melee range",
    humanCount: "{value}+ enemies in melee range",
    filters: ['facing','behind'], requires: 'UnitXP_SP3 (for count)' },
  { name: 'inrange', scope: 'target', cat: 'Range & Position', type: 'spellCount', negatable: true,
    human: "In range of {spell}", humanNeg: "Not in range of {spell}", requires: 'UnitXP_SP3 (for count)' },
  { name: 'outrange', scope: 'target', cat: 'Range & Position', type: 'spellCount', negatable: true,
    human: "Out of range of {spell}", requires: 'UnitXP_SP3 (for count)' },
  { name: 'distance', scope: 'target', cat: 'Range & Position', type: 'distanceCount', negatable: true,
    human: "Target within {value} yards",
    humanCount: "{value}+ enemies within {distance} yards",
    filters: ['facing','behind'], requires: 'UnitXP_SP3' },
  { name: 'facing', scope: 'target', cat: 'Range & Position', type: 'countMode', negatable: true,
    human: "I'm facing my target", humanNeg: "I'm not facing my target",
    humanCount: "{value}+ enemies in front of me",
    filters: ['meleerange'], requires: 'UnitXP_SP3' },
  { name: 'behind', scope: 'target', cat: 'Range & Position', type: 'countMode', negatable: true,
    human: "I'm behind my target", humanNeg: "I'm not behind my target",
    humanCount: "I'm behind {value}+ enemies",
    filters: ['meleerange'], requires: 'UnitXP_SP3' },
  { name: 'insight', scope: 'target', cat: 'Range & Position', type: 'countMode', negatable: true,
    human: "Target is in line of sight", humanNeg: "Target not in line of sight", requires: 'UnitXP_SP3' },

  // -- Relationship --
  { name: 'targeting', scope: 'target', cat: 'Relationship', type: 'value', negatable: true,
    human: "Target is targeting {value}", options: ['player','tank'], requires: 'pfUI (for tank)' },
  { name: 'member', scope: 'target', cat: 'Relationship', type: 'boolean', negatable: true,
    human: "Target is in my group", humanNeg: "Target is not in my group" },
  { name: 'party', scope: 'target', cat: 'Relationship', type: 'boolean', negatable: true,
    human: "Target is in my party", humanNeg: "Target not in my party" },
  { name: 'raid', scope: 'target', cat: 'Relationship', type: 'boolean', negatable: true,
    human: "Target is in my raid", humanNeg: "Target not in my raid" },
  { name: 'istank', scope: 'target', cat: 'Relationship', type: 'boolean', negatable: true,
    human: "Target is a tank", humanNeg: "Target is not a tank", requires: 'pfUI' },

  // -- Tags --
  { name: 'tag', scope: 'target', cat: 'Tags', type: 'boolean', negatable: true,
    human: "Target is tapped", humanNeg: "Target is not tapped" },
  { name: 'mytag', scope: 'target', cat: 'Tags', type: 'boolean', negatable: true,
    human: "I tapped the target", humanNeg: "I didn't tap the target" },
  { name: 'othertag', scope: 'target', cat: 'Tags', type: 'boolean', negatable: true,
    human: "Someone else tapped it", humanNeg: "Nobody else tapped it" },

  // -- Advanced --
  { name: 'threat', scope: 'target', cat: 'Advanced', type: 'comparison', negatable: true,
    human: "My threat is {op} {value}%", requires: 'TWThreat' },
  { name: 'tte', scope: 'target', cat: 'Advanced', type: 'comparison', negatable: true,
    human: "Time to execute is {op} {value}s", requires: 'TimeToKill' },
  { name: 'ttk', scope: 'target', cat: 'Advanced', type: 'comparison', negatable: true,
    human: "Target dies in {op} {value}s", requires: 'TimeToKill' },
  { name: 'resisted', scope: 'target', cat: 'Advanced', type: 'value', negatable: true,
    human: "Last spell was {value} resisted", options: ['full','partial'] },
  { name: 'multiscan', scope: 'target', cat: 'Advanced', type: 'value', negatable: false,
    human: "Scan for {value} enemy",
    options: ['nearest','farthest','highesthp','lowesthp','highestrawhp','lowestrawhp','markorder','skull','cross','square','moon','triangle','diamond','circle','star'],
    requires: 'UnitXP_SP3' },
  { name: 'cursive', scope: 'target', cat: 'Advanced', type: 'spellComparison', negatable: true,
    human: "Target has {spell} (GUID)", humanNeg: "Target lacks {spell} (GUID)", requires: 'Cursive' },
];
